[package]
name = "deproject-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.24.1"
anyhow = "1"
realsense-rust = "1.1.0"
realsense-sys = "2.47.0"
glow = "0.12.3"
egui_glow = "0.24.1"
bytemuck = "1.13"
glam = "0.24.1"
