[package]
name = "deproject-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.24.1"
anyhow = "1"
glow = "0.12.3"
egui_glow = "0.24.1"
glam = "0.24.1"
bytemuck = "1.13"
deproject-io = { path = "../deproject-io" }
